# home
root:
    path: /
    defaults:
        resource: "landing"
    methods: [GET, POST]
    
#action:
#    path: /{resource}{slash}{action}
#    requirements:
#        resource: "products"
#        slash: "[/]{0,1}"
#    methods: [GET, POST, PUT, DELETE]

products:
    path: /{resource}{slash}
    requirements:
        resource: "products"
        slash: "[/]{0,1}"
    methods: [GET, POST, PUT, DELETE]

productsaction:
    path: /{resource}{slash}{action}
    requirements:
        resource: "products"
        slash: "[/]{0,1}"
    methods: [GET, POST, PUT, DELETE]

monolog:
    path: /{resource}{slash}{action}
    requirements:
        resource: "monolog"
        slash: "[/]{0,1}"
    methods: [GET, DELETE]